INSERT INTO CertificationsApp_modificationstype(available_type,caption,fee, company_fee) VALUES 
('Furgon',
'caja cerrada para flete',
3000,
2700),
('Cabina simple',
'Simple, como dios lo trajo al mundo',
3000,
2700),
('Furgon termico',
'caja cerrada para flete de congelados',
3000,
2700),
('Furgon vidriado',
'Para andar seguros por el conurbano',
3000, 
2700),
('Furgon vidriado con asientos',
'El kit completo para ir a pasear por el conurbano con la family',
3000, 
2700),
('Casa rodante motorizada',
'Ahora si nos hacemos un zafari viaje por el conurbano',
3000, 
2700),
('Furgon termico con equipo de frio',
'A Dexter le gusta esto',
3000, 
2700),
('Trailer',
'Lleva tu casa rodante o tu lancha para disfrutar en el riachuelo de Sarandi',
3000, 
2700);