# Generated by Django 3.2.4 on 2021-07-29 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('mail', models.EmailField(max_length=64, unique=True)),
                ('phone', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ModificationsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_type', models.CharField(max_length=64)),
                ('caption', models.CharField(max_length=256)),
                ('fee', models.IntegerField()),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=7)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=64)),
                ('chassis_number', models.CharField(max_length=64)),
                ('engine_number', models.CharField(max_length=64)),
                ('final_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finaltype', to='CertificationsApp.modificationstype')),
                ('original_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originaltype', to='CertificationsApp.modificationstype')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='CertificationsApp.client')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=64)),
                ('stage', models.CharField(max_length=64)),
                ('registrated_at', models.DateTimeField(auto_now_add=True)),
                ('image1_uploaded', models.ImageField(upload_to='images')),
                ('image2_uploaded', models.ImageField(upload_to='images')),
                ('image3_uploaded', models.ImageField(upload_to='images')),
                ('image4_uploaded', models.ImageField(upload_to='images')),
                ('image5_uploaded', models.ImageField(upload_to='images')),
                ('image6_uploaded', models.ImageField(upload_to='images')),
                ('paid_at', models.DateTimeField(default=None)),
                ('paid_by', models.CharField(max_length=64)),
                ('doc_verified_at', models.DateTimeField(default=None)),
                ('onsite_verified_at', models.DateTimeField(default=None)),
                ('inform_created_at', models.DateTimeField(default=None)),
                ('certificate_uploaded_at', models.DateTimeField(default=None)),
                ('certificate_downloaded_at', models.DateTimeField(default=None)),
                ('final_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final', to='CertificationsApp.modificationstype')),
                ('id_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation', to='CertificationsApp.vehicle')),
                ('original_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original', to='CertificationsApp.modificationstype')),
            ],
            options={
                'verbose_name': 'operation',
                'verbose_name_plural': 'operations',
            },
        ),
    ]
