# Generated by Django 3.2.5 on 2021-07-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='certificate_downloaded_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='certificate_uploaded_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='doc_verified_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='inform_created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='onsite_verified_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='paid_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='paid_by',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
