# Generated by Django 3.1.6 on 2021-07-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0002_auto_20210730_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='final_type',
            new_name='last_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='original_type',
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modificationstype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
