# Generated by Django 3.1.6 on 2021-07-31 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0003_auto_20210731_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='CertificationsApp.client'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='id_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='CertificationsApp.vehicle'),
        ),
    ]
