# Generated by Django 3.2.4 on 2021-08-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0005_auto_20210807_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='image7_uploaded',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
