# Generated by Django 3.1.7 on 2021-08-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0007_auto_20210820_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='certificate_downloaded_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='certificate_uploaded_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='doc_verified_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image6_uploaded',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image7_uploaded',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='inform_created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='onsite_verified_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='paid_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='paid_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
