# Generated by Django 3.2.6 on 2021-09-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0009_auto_20210912_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
    ]
