# Generated by Django 3.1.7 on 2021-09-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0011_auto_20210920_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
