# Generated by Django 3.2.6 on 2021-09-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0012_auto_20210924_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='appointment',
            field=models.DateTimeField(unique=True),
        ),
    ]
