# Generated by Django 3.1.7 on 2021-09-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0013_alter_schedule_appointment'),
        ('CertificationsApp', '0012_operation_certificate'),
    ]

    operations = [
    ]
