# Generated by Django 3.2.6 on 2021-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0014_merge_20210925_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='inform_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
