# Generated by Django 3.1.7 on 2021-10-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0016_auto_20211007_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='image6_uploaded',
            field=models.ImageField(upload_to='images'),
        ),
    ]
