# Generated by Django 3.2.6 on 2021-10-11 18:52

import CertificationsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0017_auto_20211007_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modificationstype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=CertificationsApp.models.file_path),
        ),
        migrations.AlterField(
            model_name='operation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image1_uploaded',
            field=models.ImageField(upload_to='temporary'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image2_uploaded',
            field=models.ImageField(upload_to='temporary'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image3_uploaded',
            field=models.ImageField(upload_to='temporary'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image4_uploaded',
            field=models.ImageField(upload_to='temporary'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image5_uploaded',
            field=models.ImageField(upload_to='temporary'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image6_uploaded',
            field=models.ImageField(upload_to='temporary'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image7_uploaded',
            field=models.ImageField(blank=True, null=True, upload_to='temporary'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image8_uploaded',
            field=models.ImageField(blank=True, null=True, upload_to='temporary'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
