# Generated by Django 3.2.6 on 2021-10-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0019_auto_20211011_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modificationstype',
            old_name='enterpriseFee',
            new_name='company_fee',
        ),
    ]
