# Generated by Django 3.1.7 on 2021-10-13 19:28

import CertificationsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0021_auto_20211013_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='image1_uploaded',
            field=models.ImageField(upload_to=CertificationsApp.models.image_path),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image2_uploaded',
            field=models.ImageField(upload_to=CertificationsApp.models.image_path),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image3_uploaded',
            field=models.ImageField(upload_to=CertificationsApp.models.image_path),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image4_uploaded',
            field=models.ImageField(upload_to=CertificationsApp.models.image_path),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image5_uploaded',
            field=models.ImageField(upload_to=CertificationsApp.models.image_path),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image6_uploaded',
            field=models.ImageField(upload_to=CertificationsApp.models.image_path),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image7_uploaded',
            field=models.ImageField(blank=True, null=True, upload_to=CertificationsApp.models.image_path),
        ),
        migrations.AlterField(
            model_name='operation',
            name='image8_uploaded',
            field=models.ImageField(blank=True, null=True, upload_to=CertificationsApp.models.image_path),
        ),
    ]
