# Generated by Django 3.1.7 on 2021-10-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0022_auto_20211013_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mail',
            field=models.EmailField(default='abc@hotmail.com', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.IntegerField(default=123456789, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
