# Generated by Django 3.2.6 on 2022-01-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificationsApp', '0024_alter_client_id_alter_client_mail_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='inform_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
